apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: ind-cluster
spec:
  location: us-east1-b
  initialNodeCount: 1
  nodeConfig:
    machineType: e2-medium
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    preemptible: true
  autopilot: false
